import type { AiReadyCatalogueProductDefinition } from "./types";
import { filamentDefaults, product, rcb, source, tdp } from "./product-factory";

export const EQUIPMENT_PRODUCTS: AiReadyCatalogueProductDefinition[] = [
  product({
    title: "Polymaker PolyDryer",
    handle: "polymaker-polydryer",
    sku: "PM-POLYDRYER",
    description:
      "Filament drying and storage system for keeping moisture-sensitive materials print-ready.",
    priceAud: 129.95,
    brandName: "Polymaker",
    brandOriginCountry: "China",
    categoryHandle: "tools",
    collectionHandle: "filament-drying-storage",
    tags: ["drying-storage", "filament-dryer", "polymaker", "moisture-control"],
    source: source(
      "https://us.polymaker.com/products/polydryer",
      "https://shop.polymaker.com/cdn/shop/files/PolyDryer_ISO_Right_with_Spool_Rendering.png?crop=center&height=1200&v=1751884754&width=1200",
    ),
    three_d_printing: tdp({
      product_kind: "drying_storage",
      drying_recommended: false,
      best_for: [
        "filament drying",
        "sealed spool storage",
        "moisture troubleshooting",
      ],
      ai_search_keywords: ["PolyDryer", "filament dryer", "filament storage"],
    }),
  }),
  product({
    title: "PrintDry Filament Dryer PRO3",
    handle: "printdry-filament-dryer-pro3",
    sku: "PD-DRYER-PRO3",
    description:
      "High-capacity filament dryer for drying engineering materials and moisture-sensitive spools.",
    priceAud: 219.95,
    brandName: "PrintDry",
    brandOriginCountry: "Canada",
    categoryHandle: "tools",
    collectionHandle: "filament-drying-storage",
    tags: [
      "drying-storage",
      "filament-dryer",
      "printdry",
      "engineering-filament",
    ],
    source: source(
      "https://www.printdry.com/product/printdry-filament-dryer-pro3/",
      "https://www.printdry.com/wp-content/uploads/2022/12/Product-image-2.jpg",
    ),
    three_d_printing: tdp({
      product_kind: "drying_storage",
      best_for: ["engineering filament drying", "multi-spool workflows"],
      ai_search_keywords: ["PrintDry", "filament dryer"],
    }),
  }),
  product({
    title: "SUNLU FilaDryer S4",
    handle: "sunlu-filadryer-s4",
    sku: "SUNLU-FILADRYER-S4",
    description:
      "Four-spool filament dryer for drying and feeding moisture-sensitive materials during multi-printer workflows.",
    priceAud: 189.95,
    brandName: "SUNLU",
    brandOriginCountry: "China",
    categoryHandle: "tools",
    collectionHandle: "filament-drying-storage",
    tags: ["drying-storage", "filament-dryer", "sunlu", "multi-spool"],
    source: source(
      "https://store.sunlu.com/pt-es/collections/fdm-3d-printing/products/sunlu-filadryer-s4",
      "https://store.sunlu.com/cdn/shop/files/S4_eda873c5-d558-4766-9625-909b3d54c318.jpg?v=1777366218",
    ),
    three_d_printing: tdp({
      product_kind: "drying_storage",
      best_for: ["multi-spool drying", "TPU and PETG moisture control"],
      ai_search_keywords: ["SUNLU FilaDryer S4", "filament dryer"],
    }),
  }),
  product({
    title: "Magigoo Original 50ml Bed Adhesive",
    handle: "magigoo-original-50ml",
    sku: "MAGIGOO-ORIGINAL-50ML",
    description:
      "Bed adhesion aid for common 3D printing materials, useful when tuning first-layer reliability.",
    priceAud: 24.95,
    brandName: "Magigoo",
    brandOriginCountry: "Malta",
    categoryHandle: "tools",
    collectionHandle: "build-plates-surfaces",
    tags: ["bed-adhesion", "magigoo", "first-layer", "build-surface"],
    source: source(
      "https://magigoo.com/products/magigoo/",
      "https://magigoo.com/app/uploads/2019/10/Magigoo-original-2-1024x280.jpg",
    ),
    three_d_printing: tdp({
      product_kind: "maintenance_tool",
      compatible_build_surfaces: ["glass", "smooth_pei"],
      best_for: [
        "bed adhesion",
        "release layer for PETG",
        "first-layer tuning",
      ],
      ai_search_keywords: ["Magigoo", "bed adhesion", "PETG release layer"],
    }),
  }),
  product({
    title: "Bambu Lab Textured PEI Plate",
    handle: "bambu-textured-pei-plate",
    sku: "BL-TEXTURED-PEI-PLATE",
    description:
      "Bambu Lab textured PEI build plate for repeatable first layers and textured bottom surfaces.",
    priceAud: 59.95,
    brandName: "Bambu Lab",
    brandOriginCountry: "China",
    categoryHandle: "build-plates",
    collectionHandle: "bambu-lab-compatible",
    tags: ["build-surface", "textured-pei", "bambu-lab", "p1s", "x1c"],
    source: source(
      "https://us.store.bambulab.com/products/bambu-textured-pei-plate",
      "https://store.bblcdn.com/a7a47db62da5477dac7b30bb347b61a9.png",
    ),
    three_d_printing: tdp({
      product_kind: "build_surface",
      compatible_printers: ["Bambu Lab P1S", "Bambu Lab X1C"],
      compatible_build_surfaces: ["textured_pei"],
      best_for: ["PLA", "PETG", "TPU", "textured bottom finish"],
      ai_search_keywords: ["Bambu Textured PEI", "build plate"],
    }),
  }),
  product({
    title: "BIQU Panda CryoGrip Pro Build Plate",
    handle: "biqu-panda-cryogrip-pro-build-plate",
    sku: "BIQU-PANDA-CRYOGRIP-PRO",
    description:
      "BIQU/BIGTREETECH Panda CryoGrip Pro build plate for Bambu-compatible low-temperature adhesion workflows.",
    priceAud: 49.95,
    brandName: "BIQU",
    brandOriginCountry: "China",
    categoryHandle: "build-plates",
    collectionHandle: "bambu-lab-compatible",
    tags: ["build-surface", "biqu", "panda", "bambu-compatible", "cryogrip"],
    source: source(
      "https://biqu.equipment/products/biqu-panda-buildplate-cryogrip-pro",
      "https://biqu.equipment/cdn/shop/files/3010200040-CryoGrip_Pro_1000_2.jpg?v=1760705893",
    ),
    three_d_printing: tdp({
      product_kind: "build_surface",
      compatible_printers: ["Bambu Lab P1S", "Bambu Lab X1C"],
      compatible_build_surfaces: ["cryogrip"],
      best_for: [
        "low-temperature PLA adhesion",
        "Bambu-compatible build plates",
      ],
      ai_search_keywords: ["BIQU Panda CryoGrip", "Bambu build plate"],
    }),
  }),
  product({
    title: "Phaetus Rapido Hotend 2 HF",
    handle: "phaetus-rapido-hotend-2-hf",
    sku: "PHAETUS-RAPIDO2-HF",
    description:
      "China-origin high-flow all-metal hotend for fast printing and hotend upgrade workflows.",
    priceAud: 149.95,
    brandName: "Phaetus",
    brandOriginCountry: "China",
    categoryHandle: "spare-parts/hotends",
    collectionHandle: "hotend-upgrades",
    tags: ["hotend", "phaetus", "rapido", "high-flow", "china-origin"],
    source: source(
      "https://www.phaetus.com/en-us/products/rapido2",
      "https://www.phaetus.com/cdn/shop/files/phaetus-store-hotend-rapido-hotend-2-1203166968.png?v=1762424161",
    ),
    three_d_printing: tdp({
      product_kind: "hotend",
      material: "plated copper",
      max_temperature_c: 350,
      compatible_printers: [
        "Voron-compatible toolheads",
        "V6-style upgrade projects",
      ],
      best_for: ["high-flow printing", "engineering materials"],
      ai_search_keywords: ["Phaetus Rapido", "hotend upgrade", "China hotend"],
    }),
  }),
  product({
    title: "Phaetus Dragonfly Hotend BMS",
    handle: "phaetus-dragonfly-hotend-bms",
    sku: "PHAETUS-DRAGONFLY-BMS",
    description:
      "China-origin Phaetus Dragonfly BMS hotend for Creality-style hotend upgrade projects.",
    priceAud: 79.95,
    brandName: "Phaetus",
    brandOriginCountry: "China",
    categoryHandle: "spare-parts/hotends",
    collectionHandle: "hotend-upgrades",
    tags: [
      "hotend",
      "phaetus",
      "dragonfly",
      "creality-upgrade",
      "china-origin",
    ],
    source: source(
      "https://www.phaetus.com/en-us/products/dragonfly-hotend-bms",
      "https://www.phaetus.com/cdn/shop/files/phaetus-store-hotend-st-blue-1-75mm-dragonfly-hotend-bms-1203167020.png?v=1762427299",
    ),
    three_d_printing: tdp({
      product_kind: "hotend",
      material: "copper alloy",
      max_temperature_c: 500,
      compatible_printers: ["Creality Ender-series upgrade projects"],
      best_for: ["all-metal hotend upgrades", "higher-temperature materials"],
      ai_search_keywords: ["Phaetus Dragonfly BMS", "Creality hotend upgrade"],
    }),
  }),
  product({
    title: "BIQU Panda Revo Hotend for Bambu Lab",
    handle: "biqu-panda-revo-hotend-bambu",
    sku: "BIQU-PANDA-REVO-HOTEND",
    description:
      "China-origin BIQU Panda Revo drop-in hotend upgrade for selected Bambu Lab X1/P1 printers.",
    priceAud: 119.95,
    brandName: "BIQU",
    brandOriginCountry: "China",
    categoryHandle: "spare-parts/hotends",
    collectionHandle: "bambu-lab-compatible",
    tags: ["hotend", "biqu", "panda", "bambu-compatible", "china-origin"],
    source: source(
      "https://biqu.equipment/collections/all-accessories/products/biqu-panda-hotend",
      "https://biqu.equipment/cdn/shop/files/X1C_P1_6.png?v=1765372133",
      {
        official_manual_url:
          "https://global.bttwiki.com/Panda%20Revo%20X1%20Hotend.html",
      },
    ),
    three_d_printing: tdp({
      product_kind: "hotend",
      compatible_printers: ["Bambu Lab P1S", "Bambu Lab P1P", "Bambu Lab X1C"],
      best_for: ["Bambu hotend upgrades", "drop-in maintenance"],
      ai_search_keywords: ["BIQU Panda Revo", "Bambu hotend", "China hotend"],
    }),
  }),
  product({
    title: "Trianglelab CHC Pro Hotend",
    handle: "trianglelab-chc-pro-hotend",
    sku: "TRIANGLELAB-CHC-PRO",
    description:
      "China-origin ceramic-heater hotend kit for V6/Volcano-style printer upgrade projects.",
    priceAud: 49.95,
    brandName: "Trianglelab",
    brandOriginCountry: "China",
    categoryHandle: "spare-parts/hotends",
    collectionHandle: "hotend-upgrades",
    tags: ["hotend", "trianglelab", "chc-pro", "v6-compatible", "china-origin"],
    source: source(
      "https://www.trianglelab.net/products/chc-pro-hotend",
      "https://ueeshop.ly200-cdn.com/u_file/UPAT/UPAT086/2205/04/products/CHCPro-913a.jpg",
    ),
    three_d_printing: tdp({
      product_kind: "hotend",
      compatible_printers: [
        "V6-compatible hotends",
        "Volcano-style upgrade projects",
      ],
      best_for: ["quick heating", "budget hotend upgrades"],
      ai_search_keywords: ["Trianglelab CHC Pro", "China hotend"],
    }),
  }),
  product({
    title: "Trianglelab Dragon Hotend V2.0",
    handle: "trianglelab-dragon-hotend-v2",
    sku: "TRIANGLELAB-DRAGON-V2",
    description:
      "China-origin Dragon-style hotend for V6-compatible direct-drive and Bowden upgrade projects.",
    priceAud: 89.95,
    brandName: "Trianglelab",
    brandOriginCountry: "China",
    categoryHandle: "spare-parts/hotends",
    collectionHandle: "hotend-upgrades",
    tags: ["hotend", "trianglelab", "dragon", "v6-compatible", "china-origin"],
    source: source(
      "https://www.trianglelab.net/products/dragon-hotend",
      "https://ueeshop.ly200-cdn.com/u_file/UPAT/UPAT086/2411/21/products/5b4ea5cd6c.jpg",
    ),
    three_d_printing: tdp({
      product_kind: "hotend",
      compatible_printers: [
        "V6-compatible toolheads",
        "direct-drive upgrade projects",
      ],
      best_for: ["compact hotend upgrades", "high-temperature printing"],
      ai_search_keywords: ["Trianglelab Dragon", "China hotend"],
    }),
  }),
  product({
    title: "Creality Unicorn Quick-Swap Nozzle 0.4mm",
    handle: "creality-unicorn-quick-swap-nozzle-04",
    sku: "CREALITY-UNICORN-04",
    description:
      "China-origin Creality Unicorn quick-swap nozzle for K1-series and compatible Ender-3 V3 printers.",
    priceAud: 14.95,
    brandName: "Creality",
    brandOriginCountry: "China",
    categoryHandle: "spare-parts/nozzles",
    collectionHandle: "nozzles-tips",
    tags: ["nozzle", "creality", "unicorn", "k1", "china-origin"],
    source: source(
      "https://store.creality.com/eu/products/buse-unicorn-k1",
      "https://cdn.shopify.com/s/files/1/0593/2587/4251/files/Your_paragraph_text_75.png?v=1770867719",
    ),
    three_d_printing: tdp({
      product_kind: "nozzle",
      nozzle_diameter_mm: 0.4,
      material: "hardened steel",
      requires_hardened_nozzle: false,
      compatible_printers: ["Creality K1 series", "Creality Ender-3 V3 series"],
      best_for: ["quick-swap nozzle replacement", "general printing"],
      ai_search_keywords: [
        "Creality Unicorn nozzle",
        "K1 nozzle",
        "China nozzle",
      ],
    }),
  }),
  product({
    title: "Bambu Lab Hotend P1 Series 0.4mm Hardened Steel",
    handle: "bambu-hotend-p1-series-hardened-steel-04",
    sku: "BL-HOTEND-P1-HS-04",
    description:
      "Bambu Lab hardened steel hotend assembly for P1-series abrasive-filament support.",
    priceAud: 39.95,
    brandName: "Bambu Lab",
    brandOriginCountry: "China",
    categoryHandle: "spare-parts/hotends",
    collectionHandle: "bambu-lab-compatible",
    tags: ["hotend", "bambu-lab", "p1s", "hardened-steel", "china-origin"],
    source: source(
      "https://us.store.bambulab.com/products/bambu-hotend-p1-series?variant=40603093205107",
      "https://store.bblcdn.com/5b916358c07d443886fb6f6090191d58.png",
      {
        official_manual_url:
          "https://wiki.bambulab.com/en/x1/maintenance/replace-hotend",
      },
    ),
    three_d_printing: tdp({
      product_kind: "hotend",
      nozzle_diameter_mm: 0.4,
      material: "hardened steel",
      requires_hardened_nozzle: false,
      compatible_printers: ["Bambu Lab P1S", "Bambu Lab P1P", "Bambu Lab X1C"],
      best_for: ["abrasive filament printing", "Bambu hotend maintenance"],
      ai_search_keywords: ["Bambu hardened hotend", "P1S hardened nozzle"],
    }),
  }),
  product({
    title: "Mellow NF-Crazy V1 Hotend",
    handle: "mellow-nf-crazy-v1-hotend",
    sku: "MELLOW-NF-CRAZY-V1",
    description:
      "China-origin Mellow NF-Crazy all-metal hotend for V6-style Ender/CR10/Prusa upgrade projects.",
    priceAud: 54.95,
    brandName: "Mellow3D",
    brandOriginCountry: "China",
    categoryHandle: "spare-parts/hotends",
    collectionHandle: "hotend-upgrades",
    tags: ["hotend", "mellow3d", "nf-crazy", "v6-compatible", "china-origin"],
    source: source(
      "https://www.3dmellow.com/products/nf-crazy-v1-hotend",
      "https://ueeshop.ly200-cdn.com/u_file/UPBE/UPBE311/2604/30/products/ae6019ea50.jpg",
    ),
    three_d_printing: tdp({
      product_kind: "hotend",
      compatible_printers: [
        "Ender 3",
        "CR10",
        "Prusa i3 MK3S upgrade projects",
      ],
      best_for: ["budget all-metal hotend upgrades"],
      ai_search_keywords: ["Mellow NF Crazy", "China hotend"],
    }),
  }),
];
