import type { AiReadyCatalogueProductDefinition } from "./types";
import { filamentDefaults, product, rcb, source, tdp } from "./product-factory";

export const FILAMENT_PRODUCTS: AiReadyCatalogueProductDefinition[] = [
  product({
    title: "Polymaker PolyLite PETG Black 1.75mm 1kg",
    handle: "polymaker-polylite-petg-black-175-1kg",
    sku: "PM-PETG-BLK-175-1KG",
    description:
      "Source-backed PETG filament for practical functional parts, brackets, fixtures, and light outdoor use.",
    priceAud: 32.95,
    brandName: "Polymaker",
    brandOriginCountry: "China",
    categoryHandle: "filament/petg",
    collectionHandle: "premium-filaments",
    tags: [
      "filament",
      "petg",
      "polymaker",
      "outdoor-parts",
      "functional-parts",
    ],
    source: source(
      "https://us.polymaker.com/products/polylite-petg?variant=41266031198265",
      "https://shop.polymaker.com/cdn/shop/files/PolyLite-PETG_1.75mm_1kg_Clear.png?crop=center&height=1200&v=1696920905&width=1200",
    ),
    three_d_printing: tdp({
      ...filamentDefaults,
      product_kind: "filament",
      material: "PETG",
      recommended_nozzle_temp_c: { min: 230, max: 260 },
      recommended_bed_temp_c: { min: 70, max: 80 },
      compatible_build_surfaces: ["textured_pei", "satin_pei"],
      best_for: ["functional parts", "outdoor brackets"],
      not_recommended_for: ["high-temperature engine bay parts"],
      common_issues: ["stringing", "moisture sensitivity"],
      ai_search_keywords: ["PETG filament", "outdoor prints"],
    }),
    rc_model_building: rcb({
      component_role: "print_material",
      compatible_project_types: ["3d_printed_rc_car"],
      used_for: ["body panels", "light-duty brackets"],
      best_for: ["3DSets-style RC builds"],
      ai_search_keywords: ["3DSets filament", "RC body filament"],
    }),
  }),
  product({
    title: "Polymaker PLA Pro Black 1.75mm 1kg",
    handle: "polymaker-pla-pro-black-175-1kg",
    sku: "PM-PLAPRO-BLK-175-1KG",
    description:
      "Tougher PLA-class filament for prototypes, jigs, fixtures, and easier everyday printing.",
    priceAud: 31.95,
    brandName: "Polymaker",
    brandOriginCountry: "China",
    categoryHandle: "filament/pla",
    collectionHandle: "premium-filaments",
    tags: ["filament", "pla", "pla-pro", "polymaker", "beginner-friendly"],
    source: source(
      "https://us.polymaker.com/products/polymaker-pla-pro",
      "https://shop.polymaker.com/cdn/shop/files/pa13002_isometric_top_fb8ad3b7-22d3-4c39-b231-541c95612cdf.png?crop=center&height=1200&v=1773244075&width=1200",
    ),
    three_d_printing: tdp({
      ...filamentDefaults,
      product_kind: "filament",
      material: "PLA Pro",
      recommended_nozzle_temp_c: { min: 190, max: 220 },
      recommended_bed_temp_c: { min: 25, max: 60 },
      drying_recommended: false,
      compatible_build_surfaces: ["smooth_pei", "textured_pei"],
      best_for: ["prototypes", "jigs", "beginner prints"],
      not_recommended_for: ["hot car interiors"],
      ai_search_keywords: ["PLA Pro filament", "easy printing filament"],
    }),
  }),
  product({
    title: "Polymaker ASA Black 1.75mm 1kg",
    handle: "polymaker-asa-black-175-1kg",
    sku: "PM-ASA-BLK-175-1KG",
    description:
      "UV-resistant ASA filament for outdoor brackets, covers, and functional printed parts.",
    priceAud: 44.95,
    brandName: "Polymaker",
    brandOriginCountry: "China",
    categoryHandle: "filament/abs-asa",
    collectionHandle: "high-temperature-printing",
    tags: ["filament", "asa", "polymaker", "uv-resistant", "outdoor-parts"],
    source: source(
      "https://us.polymaker.com/products/polylite-asa",
      "https://shop.polymaker.com/cdn/shop/files/black.png?crop=center&height=1200&v=1731517489&width=1200",
    ),
    three_d_printing: tdp({
      ...filamentDefaults,
      product_kind: "filament",
      material: "ASA",
      recommended_nozzle_temp_c: { min: 240, max: 260 },
      recommended_bed_temp_c: { min: 75, max: 95 },
      requires_enclosure: true,
      compatible_build_surfaces: ["textured_pei", "garolite"],
      best_for: ["UV-exposed parts", "outdoor RC parts"],
      not_recommended_for: ["open-frame beginner printers"],
      common_issues: ["warping"],
      ai_search_keywords: ["ASA filament", "UV resistant filament"],
    }),
  }),
  product({
    title: "eSUN PLA+ Filament 1.75mm 1kg",
    handle: "esun-pla-plus-175-1kg",
    sku: "ESUN-PLAP-175-1KG",
    description:
      "Popular PLA+ filament for everyday prototypes, display parts, and reliable beginner printing.",
    priceAud: 27.95,
    brandName: "eSUN",
    brandOriginCountry: "China",
    categoryHandle: "filament/pla",
    collectionHandle: "beginner-friendly",
    tags: ["filament", "pla", "pla-plus", "esun", "beginner-friendly"],
    source: source(
      "https://esun3dstore.com/products/pla-pro",
      "https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB609/2409/14/products/a4274f7c3c.jpg",
    ),
    three_d_printing: tdp({
      ...filamentDefaults,
      product_kind: "filament",
      material: "PLA+",
      recommended_nozzle_temp_c: { min: 205, max: 225 },
      recommended_bed_temp_c: { min: 45, max: 60 },
      drying_recommended: false,
      compatible_build_surfaces: ["smooth_pei", "textured_pei"],
      best_for: ["visual parts", "prototypes", "beginner prints"],
      not_recommended_for: ["high-temperature parts"],
      ai_search_keywords: ["PLA+ filament", "eSUN PLA+"],
    }),
  }),
  product({
    title: "eSUN PETG Solid Filament 1.75mm 1kg",
    handle: "esun-petg-solid-175-1kg",
    sku: "ESUN-PETG-175-1KG",
    description:
      "Durable PETG filament for functional printed parts that need better toughness than PLA.",
    priceAud: 29.95,
    brandName: "eSUN",
    brandOriginCountry: "China",
    categoryHandle: "filament/petg",
    collectionHandle: "premium-filaments",
    tags: ["filament", "petg", "esun", "functional-parts"],
    source: source(
      "https://www.esun3d.com/petg-product/",
      "https://cdnus.globalso.com/esun3d/Solid-Black1.jpg",
    ),
    three_d_printing: tdp({
      ...filamentDefaults,
      product_kind: "filament",
      material: "PETG",
      recommended_nozzle_temp_c: { min: 230, max: 250 },
      recommended_bed_temp_c: { min: 75, max: 90 },
      compatible_build_surfaces: ["textured_pei", "satin_pei"],
      best_for: ["functional parts", "outdoor brackets"],
      common_issues: ["stringing"],
      ai_search_keywords: ["eSUN PETG", "PETG filament"],
    }),
  }),
  product({
    title: "eSUN eTPU-95A Flexible Filament 1.75mm 1kg",
    handle: "esun-etpu-95a-175-1kg",
    sku: "ESUN-TPU95A-175-1KG",
    description:
      "Flexible TPU 95A filament for bumpers, pads, feet, tires, and vibration-resistant parts.",
    priceAud: 39.95,
    brandName: "eSUN",
    brandOriginCountry: "China",
    categoryHandle: "filament/tpu",
    collectionHandle: "premium-filaments",
    tags: ["filament", "tpu", "flexible", "esun", "rc-bumpers"],
    source: source(
      "https://www.esun3d.com/etpu-95a-product/",
      "https://cdnus.globalso.com/esun3d/TPU-95A-TRANSLUCENT-GREEN.jpg",
    ),
    three_d_printing: tdp({
      ...filamentDefaults,
      product_kind: "filament",
      material: "TPU 95A",
      recommended_nozzle_temp_c: { min: 210, max: 230 },
      recommended_bed_temp_c: { min: 45, max: 60 },
      compatible_build_surfaces: ["textured_pei"],
      best_for: ["flexible bumpers", "vibration pads", "RC tires"],
      not_recommended_for: ["rigid brackets"],
      common_issues: ["stringing", "feeding difficulty"],
      ai_search_keywords: ["TPU filament", "flexible filament"],
    }),
    rc_model_building: rcb({
      component_role: "print_material",
      compatible_project_types: ["3d_printed_rc_car"],
      used_for: ["bumpers", "pads", "tires"],
      best_for: ["flexible RC parts"],
    }),
  }),
  product({
    title: "eSUN ABS+ Filament 1.75mm 1kg",
    handle: "esun-abs-plus-175-1kg",
    sku: "ESUN-ABSP-175-1KG",
    description:
      "Modified ABS filament for stronger enclosed-printer functional parts and heat-exposed prints.",
    priceAud: 31.95,
    brandName: "eSUN",
    brandOriginCountry: "China",
    categoryHandle: "filament/abs-asa",
    collectionHandle: "high-temperature-printing",
    tags: ["filament", "abs", "abs-plus", "esun", "enclosure-recommended"],
    source: source(
      "https://www.esun3d.com/abs-pro-product/",
      "https://cdnus.globalso.com/esun3d/ABS+-PURPLE1.jpg",
    ),
    three_d_printing: tdp({
      ...filamentDefaults,
      product_kind: "filament",
      material: "ABS+",
      recommended_nozzle_temp_c: { min: 230, max: 260 },
      recommended_bed_temp_c: { min: 80, max: 100 },
      requires_enclosure: true,
      compatible_build_surfaces: ["textured_pei", "garolite"],
      best_for: ["heat-resistant parts", "mechanical covers"],
      common_issues: ["warping", "fumes"],
      ai_search_keywords: ["ABS+ filament", "enclosed printer filament"],
    }),
  }),
  product({
    title: "Bambu Lab PLA Basic Filament 1.75mm 1kg",
    handle: "bambu-pla-basic-175-1kg",
    sku: "BL-PLA-BASIC-175-1KG",
    description:
      "Bambu Lab PLA Basic filament for easy AMS-friendly everyday printing in the Bambu ecosystem.",
    priceAud: 34.95,
    brandName: "Bambu Lab",
    brandOriginCountry: "China",
    categoryHandle: "filament/pla",
    collectionHandle: "bambu-lab-compatible",
    tags: [
      "filament",
      "pla",
      "bambu-lab",
      "ams-compatible",
      "beginner-friendly",
    ],
    source: source(
      "https://us.store.bambulab.com/en/products/pla-basic-filament",
      "https://store.bblcdn.com/s2/default/f530cee381054c5b8cb429f2d2c0b128/White.jpg",
    ),
    three_d_printing: tdp({
      ...filamentDefaults,
      product_kind: "filament",
      material: "PLA Basic",
      recommended_nozzle_temp_c: { min: 190, max: 230 },
      recommended_bed_temp_c: { min: 35, max: 45 },
      drying_recommended: false,
      compatible_printers: ["Bambu Lab P1S", "Bambu Lab X1C", "Bambu Lab A1"],
      best_for: ["everyday prints", "AMS workflows"],
      ai_search_keywords: ["Bambu PLA", "AMS filament"],
    }),
  }),
  product({
    title: "Bambu Lab PETG HF Filament 1.75mm 1kg",
    handle: "bambu-petg-hf-175-1kg",
    sku: "BL-PETGHF-175-1KG",
    description:
      "High-flow PETG filament for faster Bambu-compatible functional prints with balanced durability.",
    priceAud: 39.95,
    brandName: "Bambu Lab",
    brandOriginCountry: "China",
    categoryHandle: "filament/petg",
    collectionHandle: "bambu-lab-compatible",
    tags: ["filament", "petg", "bambu-lab", "high-flow", "functional-parts"],
    source: source(
      "https://us.store.bambulab.com/products/petg-hf",
      "https://store.bblcdn.com/4293c57a92a34c11b324197913cb25b1.jpg",
    ),
    three_d_printing: tdp({
      ...filamentDefaults,
      product_kind: "filament",
      material: "PETG HF",
      recommended_nozzle_temp_c: { min: 230, max: 260 },
      recommended_bed_temp_c: { min: 65, max: 75 },
      compatible_printers: ["Bambu Lab P1S", "Bambu Lab X1C", "Bambu Lab A1"],
      best_for: ["functional parts", "faster PETG printing"],
      common_issues: ["moisture sensitivity"],
      ai_search_keywords: ["Bambu PETG HF", "high flow PETG"],
    }),
  }),
  product({
    title: "Bambu Lab PLA-CF Black 1.75mm 1kg",
    handle: "bambu-pla-cf-black-175-1kg",
    sku: "BL-PLACF-BLK-175-1KG",
    description:
      "Carbon-fibre reinforced PLA for stiff matte parts; use a hardened nozzle for abrasive fibre-filled filament.",
    priceAud: 49.95,
    brandName: "Bambu Lab",
    brandOriginCountry: "China",
    categoryHandle: "filament/specialty",
    collectionHandle: "bambu-lab-compatible",
    tags: [
      "filament",
      "pla-cf",
      "bambu-lab",
      "carbon-fibre",
      "hardened-nozzle",
    ],
    source: source(
      "https://us.store.bambulab.com/products/pla-cf",
      "https://store.bblcdn.com/6c5ecb48a6304e16a61a49aea51e2e92.png",
    ),
    three_d_printing: tdp({
      ...filamentDefaults,
      product_kind: "filament",
      material: "PLA-CF",
      recommended_nozzle_temp_c: { min: 210, max: 240 },
      recommended_bed_temp_c: { min: 35, max: 45 },
      requires_hardened_nozzle: true,
      compatible_printers: ["Bambu Lab P1S", "Bambu Lab X1C"],
      best_for: ["stiff cosmetic parts", "matte RC body details"],
      not_recommended_for: ["brass nozzle users"],
      ai_search_keywords: [
        "PLA-CF",
        "carbon fibre filament",
        "hardened nozzle",
      ],
    }),
  }),
  product({
    title: "Bambu Lab Support for PLA/PETG 1.75mm",
    handle: "bambu-support-for-pla-petg-175",
    sku: "BL-SUPPORT-PLA-PETG-175",
    description:
      "Dedicated Bambu support material for support interfaces on PLA and PETG multi-material prints.",
    priceAud: 44.95,
    brandName: "Bambu Lab",
    brandOriginCountry: "China",
    categoryHandle: "filament/specialty",
    collectionHandle: "bambu-lab-compatible",
    tags: ["filament", "support-material", "bambu-lab", "ams-compatible"],
    source: source(
      "https://us.store.bambulab.com/products/support-for-pla-petg",
      "https://store.bblcdn.com/e4b1ce6d565d4362b6bf62facbca97e8.jpg",
    ),
    three_d_printing: tdp({
      ...filamentDefaults,
      product_kind: "filament",
      material: "Support for PLA/PETG",
      recommended_nozzle_temp_c: { min: 190, max: 240 },
      recommended_bed_temp_c: { min: 35, max: 60 },
      compatible_printers: ["Bambu Lab P1S", "Bambu Lab X1C"],
      best_for: ["support interfaces", "complex geometry"],
      not_recommended_for: ["standalone printed parts"],
      ai_search_keywords: ["support material", "Bambu support filament"],
    }),
  }),
];
