import type { AiReadyCatalogueProductDefinition } from "./types";
import { filamentDefaults, product, rcb, source, tdp } from "./product-factory";

export const RC_PRODUCTS: AiReadyCatalogueProductDefinition[] = [
  product({
    title: "Hobbywing QuicRun WP 1080 G2 Brushed ESC",
    handle: "hobbywing-quicrun-wp-1080-g2-esc",
    sku: "HW-QR-WP1080-G2",
    description:
      "Waterproof brushed ESC commonly selected for 1/10 crawler and 3D printed RC car builds.",
    priceAud: 69.95,
    brandName: "Hobbywing",
    brandOriginCountry: "China",
    categoryHandle: "electronics",
    collectionHandle: "rc-model-building",
    tags: ["rc", "esc", "hobbywing", "brushed", "crawler"],
    source: source(
      "https://www.hobbywing.com/en/products/quicrun-wp-1080-g2267",
      "https://www.hobbywing.com/en/uploads/image/20241122/55fbdaae2d5cea0e5f10f52d70c0ed14.png",
    ),
    rc_model_building: rcb({
      component_role: "esc",
      compatible_project_types: ["3d_printed_rc_car", "crawler"],
      voltage: "2-3S LiPo",
      connector_type: "customer-wired",
      used_for: ["brushed motor speed control"],
      best_for: ["1/10 crawler builds", "torque-focused RC models"],
      ai_search_keywords: ["Hobbywing 1080", "brushed ESC", "3DSets RC ESC"],
    }),
  }),
  product({
    title: "Hobbywing QuicRun WP 16BL30 G2 Brushless ESC",
    handle: "hobbywing-quicrun-wp-16bl30-g2-esc",
    sku: "HW-QR-16BL30-G2",
    description:
      "Compact waterproof brushless ESC for smaller RC projects that need sensorless brushless drive.",
    priceAud: 59.95,
    brandName: "Hobbywing",
    brandOriginCountry: "China",
    categoryHandle: "electronics",
    collectionHandle: "rc-model-building",
    tags: ["rc", "esc", "hobbywing", "brushless", "waterproof"],
    source: source(
      "https://www.hobbywing.com/en/products/quicrun-wp-16bl30-g2",
      "https://www.hobbywing.com/en/uploads/image/20250324/82dd233e05666c90bb8a8b34b3a7f0ba.png",
    ),
    rc_model_building: rcb({
      component_role: "esc",
      compatible_project_types: ["3d_printed_rc_car"],
      voltage: "2-3S LiPo",
      connector_type: "customer-wired",
      used_for: ["brushless motor speed control"],
      best_for: ["compact RC builds"],
      ai_search_keywords: ["Hobbywing 16BL30", "brushless ESC"],
    }),
  }),
  product({
    title: "FlySky FS-GT5 6CH Surface Transmitter",
    handle: "flysky-fs-gt5-6ch-transmitter",
    sku: "FS-GT5-TX",
    description:
      "Six-channel surface radio transmitter for RC car and crawler builds that need multiple auxiliary channels.",
    priceAud: 119.95,
    brandName: "FlySky",
    brandOriginCountry: "China",
    categoryHandle: "electronics",
    collectionHandle: "rc-model-building",
    tags: ["rc", "transmitter", "flysky", "surface-radio", "6-channel"],
    source: source(
      "https://www.flyskytech.com/products_detail/33.html",
      "https://www.flyskytech.com/u_file/photo/20251011/be5fe9e9c8.png",
    ),
    rc_model_building: rcb({
      component_role: "transmitter",
      compatible_project_types: ["3d_printed_rc_car", "crawler"],
      used_for: ["steering and throttle control", "auxiliary channel control"],
      best_for: ["multi-channel RC builds"],
      ai_search_keywords: ["FlySky FS-GT5", "RC transmitter", "3DSets radio"],
    }),
  }),
  product({
    title: "FlySky FS-BS6 Receiver",
    handle: "flysky-fs-bs6-receiver",
    sku: "FS-BS6-RX",
    description:
      "FlySky receiver for pairing compatible transmitters with RC car electronics builds.",
    priceAud: 34.95,
    brandName: "FlySky",
    brandOriginCountry: "China",
    categoryHandle: "electronics",
    collectionHandle: "rc-model-building",
    tags: ["rc", "receiver", "flysky", "surface-radio"],
    source: source(
      "https://www.flysky-cn.com/bs6shuoming",
      "https://static1.squarespace.com/static/5bc852d6b9144934c40d499c/t/5f99193d33275461f6ad4982/1603868992825/%E5%AF%8C%E6%96%AF%E6%96%B0LOGO%282%29.jpg?format=1500w",
      { image_policy: "official_product_image_pending_review" },
    ),
    rc_model_building: rcb({
      component_role: "receiver",
      compatible_project_types: ["3d_printed_rc_car", "crawler"],
      used_for: ["radio receiver installation"],
      best_for: ["FlySky transmitter pairing"],
      ai_search_keywords: ["FlySky receiver", "FS-BS6"],
    }),
  }),
  product({
    title: "RadioMaster MT12 Surface Radio Controller",
    handle: "radiomaster-mt12-surface-radio-controller",
    sku: "RM-MT12",
    description:
      "Open-source surface radio controller for RC cars, crawlers, boats, and complex model-control setups.",
    priceAud: 179.95,
    brandName: "RadioMaster",
    brandOriginCountry: "China",
    categoryHandle: "electronics",
    collectionHandle: "rc-model-building",
    tags: ["rc", "transmitter", "radiomaster", "surface-radio", "elrs"],
    source: source(
      "https://www.radiomasterrc.com/products/mt12-surface-radio-controller",
      "https://radiomasterrc.com/cdn/shop/files/MT12-1000x1000-1.jpg?v=1750061352",
    ),
    rc_model_building: rcb({
      component_role: "transmitter",
      compatible_project_types: ["3d_printed_rc_car", "crawler", "boat"],
      used_for: ["steering and throttle control", "custom radio mixes"],
      best_for: ["advanced RC builders"],
      ai_search_keywords: [
        "RadioMaster MT12",
        "surface radio",
        "ELRS transmitter",
      ],
    }),
  }),
  product({
    title: "RC Printer 540 Motor + 60A ESC Combo Kit",
    handle: "rcprinter-540-motor-60a-esc-combo-kit",
    sku: "RCP-540-60A-COMBO",
    description:
      "Motor and ESC combo kit sold for 3D printed RC car builds, useful as a compact starter electronics bundle.",
    priceAud: 74.95,
    brandName: "RC Printer",
    brandOriginCountry: "United States",
    categoryHandle: "electronics",
    collectionHandle: "rc-model-building",
    tags: ["rc", "motor", "esc", "combo-kit", "3d-printed-rc"],
    source: source(
      "https://rcprinter.com/products/540-motor-60a-esc-combo-kit",
      "https://rcprinter.com/cdn/shop/products/Motor1.jpg?v=1629689764",
    ),
    rc_model_building: rcb({
      component_role: "drive_motor",
      compatible_project_types: ["3d_printed_rc_car"],
      voltage: "2-3S LiPo",
      connector_type: "bullet/ESC dependent",
      used_for: ["drive motor", "speed control"],
      best_for: ["starter 3D printed RC builds"],
      ai_search_keywords: [
        "RC Printer 540 motor",
        "3D printed RC car electronics",
      ],
    }),
  }),
  product({
    title: "AGFRC B53BHLW Waterproof Servo",
    handle: "agfrc-b53bhlw-waterproof-servo",
    sku: "AGFRC-B53BHLW",
    description:
      "Programmable waterproof RC servo for steering and auxiliary actuation in demanding RC builds.",
    priceAud: 89.95,
    brandName: "AGFRC",
    brandOriginCountry: "China",
    categoryHandle: "electronics",
    collectionHandle: "rc-model-building",
    tags: ["rc", "servo", "agfrc", "waterproof", "steering"],
    source: source(
      "https://www.agfrc.com/index.php?id=2622",
      "https://www.agfrc.com/res/202202/28/2039681e832303a3.png",
    ),
    rc_model_building: rcb({
      component_role: "servo",
      compatible_project_types: ["3d_printed_rc_car", "crawler"],
      voltage: "6-8.4V",
      connector_type: "JR/Futaba-style servo plug",
      used_for: ["steering", "servo-actuated functions"],
      best_for: ["water-resistant steering setups"],
      ai_search_keywords: [
        "AGFRC servo",
        "waterproof RC servo",
        "3DSets servo",
      ],
    }),
  }),
  product({
    title: "Avid RC 5x10x4 Revolution Bearing Set",
    handle: "avid-rc-5x10x4-revolution-bearing-set",
    sku: "AVID-MR105-RSZ",
    description:
      "5x10x4mm RC bearing set for drivetrain, wheel, and rotating assemblies where the model BOM calls for MR105 sizing.",
    priceAud: 18.95,
    brandName: "Avid RC",
    brandOriginCountry: "United States",
    categoryHandle: "motion/bearings",
    collectionHandle: "rc-model-building",
    tags: ["rc", "bearings", "5x10x4", "mr105", "hardware"],
    source: source(
      "https://www.avidrc.com/product/1/bearings/1/5x10x4-Revolution-MR105-RSZ-bearings.html",
      "https://www.avidrc.com/shop/images/products/large_1_566f2012de917.jpg",
    ),
    rc_model_building: rcb({
      component_role: "bearing_set",
      compatible_project_types: ["3d_printed_rc_car"],
      used_for: ["wheel hubs", "drivetrain rotation", "gearbox support"],
      best_for: ["MR105 bearing replacement"],
      ai_search_keywords: [
        "5x10x4 bearing",
        "MR105 bearing",
        "3DSets bearings",
      ],
    }),
  }),
  product({
    title: "INJORA M3/M4 Metal Screws and Nuts Box",
    handle: "injora-m3-m4-metal-screws-nuts-box",
    sku: "INJORA-M3-M4-SCREW-BOX",
    description:
      "RC crawler screw and nut assortment useful for 3D printed RC model assembly and field repairs.",
    priceAud: 24.95,
    brandName: "INJORA",
    brandOriginCountry: "China",
    categoryHandle: "accessories",
    collectionHandle: "rc-model-building",
    tags: ["rc", "fasteners", "m3", "m4", "injora", "hardware"],
    source: source(
      "https://www.injora.com/products/injora-m3-m4-metal-screws-nuts-box-for-1-10-rc-crawler-copy",
      "https://www.injora.com/cdn/shop/products/product-image-1447821978.jpg?v=1747897743",
    ),
    rc_model_building: rcb({
      component_role: "fastener_kit",
      compatible_project_types: ["3d_printed_rc_car", "crawler"],
      used_for: ["chassis assembly", "servo mounts", "body hardware"],
      best_for: ["RC assembly spares"],
      ai_search_keywords: [
        "INJORA screw kit",
        "M3 RC fasteners",
        "3DSets hardware",
      ],
    }),
  }),
  product({
    title: "Amass XT60 Connector Pack",
    handle: "amass-xt60-connector-pack",
    sku: "AMASS-XT60-PACK",
    description:
      "XT60 connector pack for RC battery and ESC wiring where a model BOM calls for XT60 power connectors.",
    priceAud: 9.95,
    brandName: "Amass",
    brandOriginCountry: "China",
    categoryHandle: "electronics",
    collectionHandle: "rc-model-building",
    tags: ["rc", "connector", "xt60", "amass", "battery-connector"],
    source: source(
      "https://www.amassconnectors.com/pages/products-3g.html",
      "https://www.amassconnectors.com/pictures/amass.jpg",
    ),
    rc_model_building: rcb({
      component_role: "connector_pack",
      compatible_project_types: ["3d_printed_rc_car", "crawler"],
      voltage: "DC 500V class connector family",
      connector_type: "XT60",
      used_for: ["battery leads", "ESC power wiring"],
      best_for: ["RC power connector standardization"],
      ai_search_keywords: ["XT60 connector", "Amass connector", "RC wiring"],
    }),
  }),
];
