import { model } from "@medusajs/framework/utils"

export const AiProductDraft = model.define("ai_product_draft", {
  id: model.id({ prefix: "aipd" }).primaryKey(),
  status: model.text().default("received"),
  packet_version: model.number().default(1),
  source_agent: model.text().default("hermes"),
  product_id: model.text().nullable(),
  product_handle: model.text().nullable(),
  product_input: model.json().nullable(),
  source_summary: model.json().nullable(),
  raw_packet: model.json().nullable(),
  normalized_draft: model.json().nullable(),
  sources: model.json().nullable(),
  warnings: model.json().nullable(),
  confidence_summary: model.json().nullable(),
  validation_errors: model.json().nullable(),
  normalizer: model.text().nullable(),
  normalizer_trace_id: model.text().nullable(),
  admin_notes: model.text().nullable(),
  rejection_reason: model.text().nullable(),
  approved_by: model.text().nullable(),
  approved_at: model.dateTime().nullable(),
  rejected_by: model.text().nullable(),
  rejected_at: model.dateTime().nullable(),
  imported_by: model.text().nullable(),
  imported_at: model.dateTime().nullable(),
  import_summary: model.json().nullable(),
})
