#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ECC_ROOT="${1:-${ECC_SOURCE_ROOT:-/Users/kurt/Projects/everything-claude-code}}"

require_file() {
  local path="$1"
  if [[ ! -f "$path" ]]; then
    printf 'Missing required file: %s\n' "$path" >&2
    exit 1
  fi
}

copy_file() {
  local src="$1"
  local dest="$2"
  mkdir -p "$(dirname "$dest")"
  cp "$src" "$dest"
}

copy_dir_contents() {
  local src_dir="$1"
  local dest_dir="$2"
  mkdir -p "$dest_dir"
  find "$src_dir" -maxdepth 1 -type f | while IFS= read -r file; do
    cp "$file" "$dest_dir/"
  done
}

require_file "$ECC_ROOT/.codex/config.toml"
require_file "$ECC_ROOT/.codex/AGENTS.md"
require_file "$PROJECT_ROOT/.codex/config.project.toml"

mkdir -p "$PROJECT_ROOT/.codex/agents"
mkdir -p "$PROJECT_ROOT/.claude/commands"
mkdir -p "$PROJECT_ROOT/.claude/enterprise"
mkdir -p "$PROJECT_ROOT/.claude/research"
mkdir -p "$PROJECT_ROOT/.claude/rules/common"
mkdir -p "$PROJECT_ROOT/.claude/rules/typescript"
mkdir -p "$PROJECT_ROOT/.claude/skills/everything-claude-code"
mkdir -p "$PROJECT_ROOT/.claude/team"
mkdir -p "$PROJECT_ROOT/.agents/skills/everything-claude-code/agents"

{
  printf '# Generated by scripts/sync-ecc-project.sh from %s\n' "$ECC_ROOT"
  printf '# Do not edit this file directly. Update .codex/config.project.toml or pull the upstream ECC repo, then re-run the sync script.\n\n'
  cat "$ECC_ROOT/.codex/config.toml"
  printf '\n\n# Project overlay\n\n'
  cat "$PROJECT_ROOT/.codex/config.project.toml"
  printf '\n'
} > "$PROJECT_ROOT/.codex/config.toml"

copy_file "$ECC_ROOT/.codex/AGENTS.md" "$PROJECT_ROOT/.codex/AGENTS.md"
copy_file "$ECC_ROOT/.codex/agents/explorer.toml" "$PROJECT_ROOT/.codex/agents/explorer.toml"
copy_file "$ECC_ROOT/.codex/agents/reviewer.toml" "$PROJECT_ROOT/.codex/agents/reviewer.toml"
copy_file "$ECC_ROOT/.codex/agents/docs-researcher.toml" "$PROJECT_ROOT/.codex/agents/docs-researcher.toml"

copy_file "$ECC_ROOT/.claude/ecc-tools.json" "$PROJECT_ROOT/.claude/ecc-tools.json"
copy_file "$ECC_ROOT/.claude/identity.json" "$PROJECT_ROOT/.claude/identity.json"
copy_file "$ECC_ROOT/.claude/enterprise/controls.md" "$PROJECT_ROOT/.claude/enterprise/controls.md"
copy_file "$ECC_ROOT/.claude/research/everything-claude-code-research-playbook.md" "$PROJECT_ROOT/.claude/research/everything-claude-code-research-playbook.md"
copy_file "$ECC_ROOT/.claude/team/everything-claude-code-team-config.json" "$PROJECT_ROOT/.claude/team/everything-claude-code-team-config.json"
copy_file "$ECC_ROOT/.claude/skills/everything-claude-code/SKILL.md" "$PROJECT_ROOT/.claude/skills/everything-claude-code/SKILL.md"
copy_file "$ECC_ROOT/.claude/commands/add-language-rules.md" "$PROJECT_ROOT/.claude/commands/add-language-rules.md"
copy_file "$ECC_ROOT/.claude/commands/database-migration.md" "$PROJECT_ROOT/.claude/commands/database-migration.md"
copy_file "$ECC_ROOT/.claude/commands/feature-development.md" "$PROJECT_ROOT/.claude/commands/feature-development.md"

copy_dir_contents "$ECC_ROOT/rules/common" "$PROJECT_ROOT/.claude/rules/common"
copy_dir_contents "$ECC_ROOT/rules/typescript" "$PROJECT_ROOT/.claude/rules/typescript"

copy_file "$ECC_ROOT/.agents/skills/everything-claude-code/SKILL.md" "$PROJECT_ROOT/.agents/skills/everything-claude-code/SKILL.md"
copy_file "$ECC_ROOT/.agents/skills/everything-claude-code/agents/openai.yaml" "$PROJECT_ROOT/.agents/skills/everything-claude-code/agents/openai.yaml"

printf 'Synced ECC project adapter from %s\n' "$ECC_ROOT"
